apiVersion: batch/v1
kind: Job
metadata:
  name: ${nodeName}kube
spec:
  template:
    spec:
      nodeName: ${nodeName}
      containers:
      - name: my-container
        image: nginx:latest
      restartPolicy: Never
